//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Information
    {
        public int Company_Info_ID { get; set; }
        public decimal VAT_Percentage { get; set; }
        public decimal Mark_Up_Percentage { get; set; }
        public string Adress { get; set; }
    }
}
