//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Order()
        {
            this.Customer_Order_Line = new HashSet<Customer_Order_Line>();
        }
    
        public int Order_ID { get; set; }
        public string Order_Status { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<double> Sale_Vat_Amount { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Delivery_Status_ID { get; set; }
        public int ItemType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Delivery_Status Delivery_Status { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Order_Line> Customer_Order_Line { get; set; }
    }
}
