//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Booking_Shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Booking_Shift()
        {
            this.Employee_Attendence_Status = new HashSet<Employee_Attendence_Status>();
        }
    
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> Employee_Shift_ID { get; set; }
        public int Booking_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Attendence_Status> Employee_Attendence_Status { get; set; }
        public virtual Employee_Shifts Employee_Shifts { get; set; }
    }
}
