//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Attendence_Status
    {
        public Nullable<int> Booking_ID { get; set; }
        public string Attendence_Description { get; set; }
        public int Empployee_Attendence_ID { get; set; }
    
        public virtual Employee_Booking_Shift Employee_Booking_Shift { get; set; }
    }
}
