//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Item_Stock_Line
    {
        public Nullable<int> Stock_ID { get; set; }
        public string Stock_Item_Name { get; set; }
        public int Stock_Item_Quantity { get; set; }
        public Nullable<int> Menu_Item_ID { get; set; }
        public int Menu_Item_Stock_Line_ID { get; set; }
    
        public virtual Menu_Item Menu_Item { get; set; }
        public virtual Stock_Item Stock_Item { get; set; }
    }
}
