//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_Item()
        {
            this.Customer_Order_Line = new HashSet<Customer_Order_Line>();
            this.Menu_Item_Stock_Line = new HashSet<Menu_Item_Stock_Line>();
        }
    
        public int Menu_Item_ID { get; set; }
        public string Menu_Item_Name { get; set; }
        public string Menu_Item_Description { get; set; }
        public decimal Menu_Item_Price { get; set; }
        public Nullable<int> Menu_Item_Type_ID { get; set; }
        public Nullable<int> Menu_Price_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Order_Line> Customer_Order_Line { get; set; }
        public virtual Menu_Item_Price Menu_Item_Price1 { get; set; }
        public virtual Menu_Item_Type Menu_Item_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_Item_Stock_Line> Menu_Item_Stock_Line { get; set; }
    }
}
