//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantity1
    {
        public int Check_In_Line_ID { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public Nullable<int> Check_In_ID { get; set; }
    }
}
