//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int Special_ID { get; set; }
        public string Special_Description { get; set; }
        public System.DateTime Special_Start_Date { get; set; }
        public System.DateTime Special_End_Date { get; set; }
        public double Special_Discount { get; set; }
    }
}
