//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_WriteOff_Line
    {
        public int Stock_WriteOff_LineID { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public Nullable<int> Write_Off_ID { get; set; }
        public string Stock_Item_Name { get; set; }
    
        public virtual Stock_Item Stock_Item { get; set; }
        public virtual Stock_Write_Off Stock_Write_Off { get; set; }
    }
}
