//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_Item()
        {
            this.Check_In_Line = new HashSet<Check_In_Line>();
            this.Check_Out_Line = new HashSet<Check_Out_Line>();
            this.Customer_Order_Line = new HashSet<Customer_Order_Line>();
            this.Stock_Combo_Line = new HashSet<Stock_Combo_Line>();
            this.Stock_Order_Line = new HashSet<Stock_Order_Line>();
            this.Stock_WriteOff_Line = new HashSet<Stock_WriteOff_Line>();
        }
    
        public int Stock_ID { get; set; }
        public string Stock_Item_Name { get; set; }
        public int Stock_Item_Quantity { get; set; }
        public string Stock_Item_Description { get; set; }
        public Nullable<int> Stock_Type_ID { get; set; }
        public Nullable<int> Stock_Price_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check_In_Line> Check_In_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check_Out_Line> Check_Out_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Order_Line> Customer_Order_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Combo_Line> Stock_Combo_Line { get; set; }
        public virtual Stock_Price Stock_Price { get; set; }
        public virtual Stock_Type Stock_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Order_Line> Stock_Order_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_WriteOff_Line> Stock_WriteOff_Line { get; set; }
    }
}
