//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Order_Line
    {
        public Nullable<int> Stock_ID { get; set; }
        public Nullable<int> Stock_Order_ID { get; set; }
        public int Stock_Order_Quantity { get; set; }
        public int Quantity_Received { get; set; }
        public int Stock_Order_Line_ID { get; set; }
    
        public virtual Stock_Item Stock_Item { get; set; }
        public virtual Stock_Order Stock_Order { get; set; }
    }
}
