//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suburb
    {
        public int Suburb_ID { get; set; }
        public string Suburb_Name { get; set; }
        public int Zip_Code { get; set; }
        public Nullable<int> City_ID { get; set; }
    
        public virtual City City { get; set; }
    }
}
