//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Contact_Details
    {
        public int Supplier_Contact_ID { get; set; }
        public string Supplier_Contact_Name { get; set; }
        public int Supplier_Contact_Number { get; set; }
        public string Supplier_Email_Adress { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
